### ISSUE TITLE
Filtering on Nested Collections

### ISSUE THREAD

**Issue by AdrianMcGrathRiptide** [boylesoftware/x2node-dbos#7]
Just a question. We only perform soft deletions in our system, so we have a model design such that every entity has a status field with two values: ACTIVE, DELETED

I will refer to the Order and OrderItem examples in the documentation for this. Consider a situation where a user is constructing an Order, with several OrderItems. They choose to delete an OrderItem from their order. In our system, the OrderItem's status flag would be set to DELETED.

When retrieving the Order, we would join the OrderItem list in to the response. We would not want to include the "deleted" OrderItem in the OrderItem list. How would we tell x2node to filter the collection to exclude OrderItems where status == DELETED?

After going through the documentation, all I found was in relation to creating a View with static filtering specifications. We were hoping there would be a better solution than that. For one, we are wanting to try to avoid using views in general, and for two, we were hoping for a more dynamic solution. Does x2node have the ability to do what we are attempting to do?

**Comment by levahim** [comment]
The way to do it in x2node is to use property views ("viewOf" attribute on the property definition). Note, that those are not SQL database views, you don't create any special objects in the database for that. The basic technique for creating filtered views of collection properties is described here: https://github.com/boylesoftware/x2node-dbos#filtered-collection-views. This is a very lightweight solution. All it does is it adds the condition to the join when the filtered collection view property is requested. Note also that since it is a view property, it is not included in the fetched properties by default and it needs to be explicitly requested. You can do some tricks with overriding the default property inclusion logic: e.g. use "fetchByDefault" property definition attribute to hide the collection property that includes all of your items--active and deleted--and include the filtered view property in the default set of fetched properties. You can also use fetch query parameters in the filters via the `dbo.param()` function, but that doesn't appear to be what you need in your case. Let me know if it doesn't answer your question!
